########## BoCA component makefile ##########

# Change these variables to fit your project:
TARGET	  = superlame
TYPE	  = encoder
VERSION	  = 1.0

BOCA_PATH = ../..

# Enter object files here:
OBJECTS	  = config.o dllinterface.o framecrc.o lame.o repacker.o worker.o

# Enter additional defines here:
DEFINE	  =

# Enter additional library dependencies here:
LIBS	  =

# Enter addition commands for targets all and clean here:
ALLCMD1   =
ALLCMD2   =
CLEANCMD1 =
CLEANCMD2 =
INSTCMD1  =
INSTCMD2  = 
UINSTCMD1 =
UINSTCMD2 =

## Do not change anything below this line. ##

include $(dir $(firstword $(MAKEFILE_LIST)))/$(BOCA_PATH)/Makefile-commands
